# Generated by Django 4.2 on 2024-12-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StucturalTechExpertsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
