# Generated by Django 4.2 on 2024-12-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StucturalTechExpertsapp', '0005_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
